name: deploy
on:
  push:
  pull_request:
    branches:
    - master
jobs:
  commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm i
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run build
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm i
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run build
      - run: npm run analyze
      - run: npm run validate
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
